[project]
name = "comticket"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "beautifulsoup4 (>=4.13.5,<5.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "parsel (>=1.10.0,<2.0.0)",
    "lxml (>=6.0.1,<7.0.0)",
    "zai-sdk (>=0.0.3.5,<0.0.4.0)"
]

[tool.poetry]
packages = [{include = "comticket", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
